import type { AnalyzerConfig } from "../types"

export const DEFAULT_CONFIG: AnalyzerConfig = {
    apiDir: "src/app/api",
    outputDir: "./api-analysis",
    includePatterns: ["**/*.ts", "**/*.js", "**/*.tsx"],
    excludePatterns: ["**/node_modules/**", "**/*.test.*", "**/*.spec.*"],
    authPatterns: [
        "authorization",
        "authenticate",
        "jwt",
        "token",
        "session",
        "auth",
        "bearer",
        "passport",
        "next-auth",
        "getServerSession",
        "getToken",
    ],
    middlewarePatterns: [
        "cors",
        "helmet",
        "rateLimit",
        "bodyParser",
        "multer",
        "expressValidator",
        "morgan",
        "compression",
        "cookieParser",
        "csrf",
        "expressSession",
        "passport",
        "nextConnect",
    ],
    enableTrends: true,
    enablePerformanceAnalysis: true,
    enableSecurityAnalysis: true,
    thresholds: {
        security: 80,
        performance: 70,
        maintainability: 75,
        testCoverage: 80,
    },
    plugins: [],
    customRules: [],
}